### ISSUE TITLE
Configure read-only access to the DB

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-wallet#10]
Create a new user with read-only access to the database and communicate this with @vgrichina @mattlockyer.

Just for the context, NEAR Indexer for Wallet is currently manually deployed (#6), and keeps syncing data in real-time into a PostgreSQL database on Render.com. Having read-only access to the DB, the Wallet team is free to implement their minimal backend to fetch the data.

@khorolets Please, add the table schema and some examples of queries to this issue, so the Wallet team has a good starting point.

**Comment by khorolets** [comment]
I've sent credentials to Slack group (@vgrichina, @mattlockyer, @frol and I)

Here is the migrations for our `access_keys` table in NEAR Indexer for Wallet. I guess it should help.

```sql
CREATE TYPE execution_status_type AS ENUM ('PENDING', 'FAILED', 'SUCCESS');
CREATE TYPE access_key_action_type AS ENUM ('ADD', 'DELETE');
CREATE TYPE access_key_permission_type AS ENUM ('NOT_APPLICABLE', 'FULL_ACCESS', 'FUNCTION_CALL');

CREATE TABLE access_keys (
    public_key text NOT NULL,
    account_id text NOT NULL,
    "action" access_key_action_type NOT NULL,
    status execution_status_type NOT NULL,
    receipt_hash text NOT NULL,
    block_height numeric(20) NOT NULL, -- numeric(precision) 20 digits should be enought to store u64::MAX
    "permission" access_key_permission_type NOT NULL,
    CONSTRAINT access_keys_pk PRIMARY KEY (public_key, account_id, "action", receipt_hash)
);
CREATE INDEX access_keys_public_key_idx ON access_keys (public_key);
CREATE INDEX access_keys_account_id_idx ON access_keys (account_id);
CREATE INDEX access_keys_block_height_idx ON access_keys (block_height);
CREATE INDEX access_keys_receipt_hash_idx ON access_keys (receipt_hash);
```

**Comment by khorolets** [comment]
Example select query to start with:

```sql
SELECT "action"
FROM access_keys
WHERE public_key = :public_key AND account_id = :account_id AND status = 'SUCCESS'
ORDER BY block_height DESC
LIMIT 1
```

So if the last `"action"`is `ADD` that the `public_key` exists. if `DELETE` than it doesn't exist.
