### ISSUE TITLE
Index functionCalls through multi-sig contract

### ISSUE THREAD

**Issue by kcole16** [near/near-indexer-for-wallet#13]
### Overview
When using a multi-sig contract, the actual transaction always appears as a functionCall `add_request_and_confirm` to the user's own account (since the multi-sig is deployed to their account), and doesn't show the underlying transaction. This makes it difficult for users to review their transaction history. 

For every user with a multi-sig contract, we'd like to index all calls to `add_request_and_confirm` and the arguments for this function call. 

**Example:**
User's account name: `seed.testnet`
Multi-sig is deployed to the account: `seed.testnet`

For every functionCall `add_request_and_confirm` to `seed.testnet`, index:
```
receiver_id: <receiver_id>
actions: <actions_json>
```
 Sample TX: https://explorer.testnet.near.org/transactions/JYsAsxG3GShHu6cM9TjwLbe2RJ2g4YzvjVLuVteQnfw

**Comment by kcole16** [comment]
cc @mattlockyer @vgrichina 

There is probably a lot more we can do here. Do you think this is specific enough (or too specific)?

**Comment by kcole16** [comment]
Potentially we can just index the arguments from the functionCalls, and build these into user friendly descriptions

**Comment by mattlockyer** [comment]
It's a bit more complicated that just the functionCall args for multisig contracts...
If you look at these calls: https://explorer.testnet.near.org/accounts/qz4.testnet

multisig contract: `add_request_and_confirm`, you see args that form the multisig request but NO request_id. This request hasn't actually executed yet, it's just stored on chain. We need those args to be indexed with the request_id of the contract for that account which can be obtained by calling `get_request_nonce` on the contract (accountId).

Then when `confirm` is called, passing `request_id` as arg, we will know if the tx succeeds that the arguments in the request have executed the underlying tx.

Update:
@khorolets is the indexer able to make an additional rpc call to gather more data when it sees a specific function call?

**Comment by khorolets** [comment]
> @khorolets is the indexer able to make an additional rpc call to gather more data when it sees a specific function call?

Indexer can rely on Receipts and ExecutionOutocome for Receipts. 

So for example it get Receipt with functionCall, stores the data. Later it get ExecutionOutcome for this Receipt and updates the data in database. Currently it make like this for AddKey and DeleteKey actions to store AccessKeys

**Comment by mattlockyer** [comment]
@khorolets had a chat with @kcole16 and now can better describe the situation with multisig contracts.

## What we need to query and show in wallet for each AccountId
More details on what we want here: https://github.com/near/near-explorer/issues/337

We would like to show the results of a **confirmed multisig transaction and all actions executed** like this:
![image](https://user-images.githubusercontent.com/321340/90804456-1b28fc80-e2cf-11ea-86f6-4e1c3eb11d2a.png)

## Background on multisig contract, requests and actions:

1. The multisig contract has it's own nonce for each request. A request can have many actions.
2. Once a request is added, the nonce is incremented, but the actions are not executed yet.
3. A final call to `confirm` with arg `request_id` matching request nonce, will execute the request and remove it from contract storage, the nonce is unchanged here and is never decremented.
4. If a `confirm` tx is successful, all of the actions in the request were successful.

For a given accountId, we need the outcome of **all request actions** indexed to show this in the wallet / explorer activity (a sample of what we want to show pictured above).

1. The multisig nonce is here: https://github.com/near/core-contracts/blob/cad998e428305f6eb3a07823e73f0867709bfa12/multisig/src/lib.rs#L88

2. Request and Actions:
`add_request, add_request_and_confirm` will add a request, the transaction action looks like this:
```
args: "eyJyZXF1ZXN0Ijp7InJlY2VpdmVyX2lkIjoiYS50ZXN0bmV0IiwiYWN0aW9ucyI6W3siZGVwb3NpdCI6IjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJ0eXBlIjoiVHJhbnNmZXIiLCJhbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIn1dfX0="
deposit: "0"
gas: 100000000000000
method_name: "add_request_and_confirm"
```
args is just base64 encoded and looks like this (for transfer):
```
{
  request: {
    receiver_id: [accountId],
    actions: [{
      type: "Transfer",
      amount: [U128],
    }]
  }
}
```
For all multisig request actions see: https://github.com/near/core-contracts/blob/cad998e428305f6eb3a07823e73f0867709bfa12/multisig/src/lib.rs#L29-L67

3/4: Confirmation and execution of the request:
https://github.com/near/core-contracts/blob/cad998e428305f6eb3a07823e73f0867709bfa12/multisig/src/lib.rs#L172-L231

An example account:
https://explorer.testnet.near.org/accounts/qz5.testnet

### NOTE I am unfamiliar with
> Receipts and ExecutionOutocome for Receipts

How much information, from steps 3/4, execution of multisig request actions in the tx receipt is available???
I do not know if you can see the "internal" actions of the **contract runtime** from only these receipts.

**Comment by mattlockyer** [comment]
@khorolets as per @vgrichina comment on Slack - It makes sense to keep general e.g. store functionCall args in jsonb so we can query efficiently in the future.

In multisig case above - my only concern is that we can query request actions AND verify it request was confirmed successfully, so we can show all request actions as being "confirmed" in the wallet activity.

Otherwise it's basically storing functionCall args and allowing us to query by accountId and method_name.

**Comment by frol** [comment]
Done in https://github.com/near/near-indexer-for-explorer (store all the receipts in DB)
