### ISSUE TITLE
Dump all transaction data in flexible format in DB for processing

### ISSUE THREAD

**Issue by vgrichina** [near/near-indexer-for-wallet#17]
It's very hard to experiment with app-specific data processing with current indexer:
- requires understanding of nearcore internals / Rust specifics
- clean debug build takes around 30 minutes easily
- incremental build for trivial changes takes around 1 minute

Ideal for the wallet would be to extract following into DB:
- `Transactions` table with everything related to given transaction besides actions. From wallet POV "receipts" are also transactions and should be included here with reference to their parent.
- `Actions` table which is basically transactionId, actionIndex, actionData (this one can just be  JSONB  so  that no need to handcode individual actions. Postgres can index / query it efficiently it as necessary.)

Then for any kind of info we are interested in we can just spend few minutes making an SQL query and exposing API endpoint in near-contract-helper.

Note that if we find that historical transactions take too much space and we don't want to keep them – it's possible to do whatever post processing needed externally (e.g. by running SQL query) and remove old transactions from DB. However it looks like for wallet needs we really need to keep most transactions anyway (to be able to show activity history in UI).

**Comment by frol** [comment]
I suggest having a separate table for actions as they can be arbitrary big (the Deploy action includes the blob of the binary contract and it is not unusual to see it 500kb; FunctionCall arguments can also be huge, see Rainbow Bridge). I would even consider moving those blobs to a blob storage off the DB (we strip away these on the current Explorer backend for this specific reason)

**Comment by vgrichina** [comment]
@frol for wallet purposes we probably can just cut off arguments blob at certain size

**Comment by mattlockyer** [comment]
@frol @khorolets 
Bump on this. Currently with explorer API I'll be unable to tell if 2FA account has called staking methods on validator, because actions.args is relatively shallow. It does not provide any details about multisig request args.

![image](https://user-images.githubusercontent.com/321340/93275075-c31bd380-f770-11ea-8613-9c1175ad8f4c.png)

It looks like for explorer there's additional RPC call when looking at a single transaction, but this won't work for query into multisig requests:
https://github.com/near/near-explorer/blob/master/frontend/src/libraries/explorer-wamp/transactions.ts

Here's the query I would like to perform:
```
SELECT
            transactions.hash, 
            transactions.signer_id,
            transactions.receiver_id,
            transactions.block_timestamp, 
            actions.action_type as kind, 
            actions.action_args as args
        FROM 
            transactions
        LEFT JOIN actions ON actions.transaction_hash = transactions.hash
        WHERE 
            transactions.signer_id = :accountId
            AND
            (
                (
                    json_extract(actions.action_args, '$.method_name') like '%stake'
                    AND
                    transactions.receiver_id in (:validators)
                )
                OR
                (
                    json_extract(actions.action_args, '$.method_name') = 'add_request_and_confirm'
                    AND
                    json_extract(actions.action_args, '$.request.actions.method_name') like '%stake'
                    AND
                    json_extract(actions.action_args, '$.request.receiver_id') in (:validators)
                )
            )   
        ORDER BY 
            block_timestamp DESC
        LIMIT 
            :offset, :count
```

**Comment by mattlockyer** [comment]
Basically trying to find txs like this using queries:
https://explorer.testnet.near.org/transactions/D9KG7DhicbxQMqAAUxacobMzBaHnnDgY4yPmDspmTKew

**Comment by frol** [comment]
Done in https://github.com/near/near-indexer-for-explorer
