### ISSUE TITLE
Extend README with some initial information

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-wallet#2]
* [ ] Express the use-case of the project
* [ ] Add NEAR Indexer link
* [ ] Provide build instructions (or reference to a relevant NEAR Indexer section if that is the same)

**Comment by khorolets** [comment]
Blocked until https://github.com/nearprotocol/nearcore/pull/3082 merged

**Comment by frol** [comment]
> Blocked

Well, you can have a draft PR ;)
