### ISSUE TITLE
Manually deploy NEAR Indexer for Wallet testnet

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-wallet#6]
We need a machine to deploy NEAR Indexer for Wallet for testnet network, which requires the same amount of resources as archival nearcore nodes. 

Let's just manually deploy the node on GCP VM.

**Comment by khorolets** [comment]
It is deployed on the google VM named `testnet-indexer-for-wallet-node0`

Running via tmux for user `ubuntu` from home dir with, storing logs in `~/indexer.log` against `testnet`.

```bash
RUST_BACKTRACE=1 ./near-indexer-for-wallet ~/.near/testnet 2>&1 | tee -a indexer.log
```

Storing the data to `Render.com` postgres `near_indexer_for_wallet_testnet`
